package com.zhaodi.oa.entity;

public class UfClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.id
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.requestId
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer requestid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.className
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.formmodeid
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer formmodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.modedatacreater
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer modedatacreater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.modedatacreatertype
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer modedatacreatertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.modedatacreatedate
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private String modedatacreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.modedatacreatetime
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private String modedatacreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.classParent
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private String classparent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.MODEUUID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private String modeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_classification.parentID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.id
     *
     * @return the value of uf_classification.id
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.id
     *
     * @param id the value for uf_classification.id
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.requestId
     *
     * @return the value of uf_classification.requestId
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getRequestid() {
        return requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.requestId
     *
     * @param requestid the value for uf_classification.requestId
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setRequestid(Integer requestid) {
        this.requestid = requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.className
     *
     * @return the value of uf_classification.className
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.className
     *
     * @param classname the value for uf_classification.className
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.formmodeid
     *
     * @return the value of uf_classification.formmodeid
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getFormmodeid() {
        return formmodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.formmodeid
     *
     * @param formmodeid the value for uf_classification.formmodeid
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setFormmodeid(Integer formmodeid) {
        this.formmodeid = formmodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.modedatacreater
     *
     * @return the value of uf_classification.modedatacreater
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getModedatacreater() {
        return modedatacreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.modedatacreater
     *
     * @param modedatacreater the value for uf_classification.modedatacreater
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setModedatacreater(Integer modedatacreater) {
        this.modedatacreater = modedatacreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.modedatacreatertype
     *
     * @return the value of uf_classification.modedatacreatertype
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getModedatacreatertype() {
        return modedatacreatertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.modedatacreatertype
     *
     * @param modedatacreatertype the value for uf_classification.modedatacreatertype
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setModedatacreatertype(Integer modedatacreatertype) {
        this.modedatacreatertype = modedatacreatertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.modedatacreatedate
     *
     * @return the value of uf_classification.modedatacreatedate
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public String getModedatacreatedate() {
        return modedatacreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.modedatacreatedate
     *
     * @param modedatacreatedate the value for uf_classification.modedatacreatedate
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setModedatacreatedate(String modedatacreatedate) {
        this.modedatacreatedate = modedatacreatedate == null ? null : modedatacreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.modedatacreatetime
     *
     * @return the value of uf_classification.modedatacreatetime
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public String getModedatacreatetime() {
        return modedatacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.modedatacreatetime
     *
     * @param modedatacreatetime the value for uf_classification.modedatacreatetime
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setModedatacreatetime(String modedatacreatetime) {
        this.modedatacreatetime = modedatacreatetime == null ? null : modedatacreatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.classParent
     *
     * @return the value of uf_classification.classParent
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public String getClassparent() {
        return classparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.classParent
     *
     * @param classparent the value for uf_classification.classParent
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setClassparent(String classparent) {
        this.classparent = classparent == null ? null : classparent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.MODEUUID
     *
     * @return the value of uf_classification.MODEUUID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public String getModeuuid() {
        return modeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.MODEUUID
     *
     * @param modeuuid the value for uf_classification.MODEUUID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setModeuuid(String modeuuid) {
        this.modeuuid = modeuuid == null ? null : modeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_classification.parentID
     *
     * @return the value of uf_classification.parentID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_classification.parentID
     *
     * @param parentid the value for uf_classification.parentID
     *
     * @mbg.generated Sat May 09 10:42:10 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}