package com.zhaodi.custom.entity;

/**
 * @author WangBo
 * @version 1.0
 * @Describe 描述
 * @date 2020/4/15 17:33
 */
public class SysCatalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.server_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private String server_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.mode_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private String mode_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.createTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.creater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private Long creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.updateTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private String updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.updater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private Long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.mode_id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    private Long mode_Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.id
     *
     * @return the value of sys_catalog.id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.id
     *
     * @param id the value for sys_catalog.id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.server_url
     *
     * @return the value of sys_catalog.server_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public String getServerUrl() {
        return server_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.server_url
     *
     * @param serverUrl the value for sys_catalog.server_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setServerUrl(String serverUrl) {
        this.server_Url = serverUrl == null ? null : serverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.mode_url
     *
     * @return the value of sys_catalog.mode_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public String getModeUrl() {
        return mode_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.mode_url
     *
     * @param modeUrl the value for sys_catalog.mode_url
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setModeUrl(String modeUrl) {
        this.mode_Url = modeUrl == null ? null : modeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.createTime
     *
     * @return the value of sys_catalog.createTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.createTime
     *
     * @param createtime the value for sys_catalog.createTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.creater
     *
     * @return the value of sys_catalog.creater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.creater
     *
     * @param creater the value for sys_catalog.creater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.updateTime
     *
     * @return the value of sys_catalog.updateTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.updateTime
     *
     * @param updatetime the value for sys_catalog.updateTime
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.updater
     *
     * @return the value of sys_catalog.updater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.updater
     *
     * @param updater the value for sys_catalog.updater
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.mode_id
     *
     * @return the value of sys_catalog.mode_id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public Long getModeId() {
        return mode_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.mode_id
     *
     * @param modeId the value for sys_catalog.mode_id
     *
     * @mbg.generated Wed Apr 15 17:32:45 CST 2020
     */
    public void setModeId(Long modeId) {
        this.mode_Id = modeId;
    }
}