package com.zhaodi.custom.entity;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleId
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleCode
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.sort
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.creater
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private Long creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.createTime
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.creatName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private String creatname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.describe
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleId
     *
     * @return the value of sys_role.roleId
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleId
     *
     * @param roleid the value for sys_role.roleId
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleName
     *
     * @return the value of sys_role.roleName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleName
     *
     * @param rolename the value for sys_role.roleName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleCode
     *
     * @return the value of sys_role.roleCode
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleCode
     *
     * @param rolecode the value for sys_role.roleCode
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.sort
     *
     * @return the value of sys_role.sort
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.sort
     *
     * @param sort the value for sys_role.sort
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.creater
     *
     * @return the value of sys_role.creater
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.creater
     *
     * @param creater the value for sys_role.creater
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.createTime
     *
     * @return the value of sys_role.createTime
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.createTime
     *
     * @param createtime the value for sys_role.createTime
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.creatName
     *
     * @return the value of sys_role.creatName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public String getCreatname() {
        return creatname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.creatName
     *
     * @param creatname the value for sys_role.creatName
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setCreatname(String creatname) {
        this.creatname = creatname == null ? null : creatname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.describe
     *
     * @return the value of sys_role.describe
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.describe
     *
     * @param describe the value for sys_role.describe
     *
     * @mbg.generated Thu May 28 10:54:38 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

}