package com.zhaodi.custom.entity;

import java.util.Date;

public class UfPatentdataWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.id
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.word
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.nature
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.status
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.creater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private long creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.creatTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private String creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.updater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf_patentdata_word.updateTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.id
     *
     * @return the value of uf_patentdata_word.id
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.id
     *
     * @param id the value for uf_patentdata_word.id
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.word
     *
     * @return the value of uf_patentdata_word.word
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.word
     *
     * @param word the value for uf_patentdata_word.word
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.nature
     *
     * @return the value of uf_patentdata_word.nature
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.nature
     *
     * @param nature the value for uf_patentdata_word.nature
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.status
     *
     * @return the value of uf_patentdata_word.status
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.status
     *
     * @param status the value for uf_patentdata_word.status
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.creater
     *
     * @return the value of uf_patentdata_word.creater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.creater
     *
     * @param creater the value for uf_patentdata_word.creater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setCreater(long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.creatTime
     *
     * @return the value of uf_patentdata_word.creatTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public String getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.creatTime
     *
     * @param creattime the value for uf_patentdata_word.creatTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setCreattime(String creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.updater
     *
     * @return the value of uf_patentdata_word.updater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.updater
     *
     * @param updater the value for uf_patentdata_word.updater
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setUpdater(long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf_patentdata_word.updateTime
     *
     * @return the value of uf_patentdata_word.updateTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf_patentdata_word.updateTime
     *
     * @param updatetime the value for uf_patentdata_word.updateTime
     *
     * @mbg.generated Wed Apr 29 13:17:58 CST 2020
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}